# Install path
export ZSH=$HOME/.oh-my-zsh

# Likes: sunaku, bureau, robbyrussell
ZSH_THEME="sunaku"

# Case-sensitive completion
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Add wisely, as too many plugins slow down shell startup.
plugins=(git git-extras sudo osx dircycle encode64 sublime)

source $ZSH/oh-my-zsh.sh

# Dotfiles
source ~/.dotfiles
source $DOTFILES/applications/zsh/config